"""empty message

Revision ID: 5d3e6aaddf7c
Revises: c5202c14d1ae
Create Date: 2019-04-15 19:23:31.116537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d3e6aaddf7c'
down_revision = 'c5202c14d1ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('fresh', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'fresh')
    # ### end Alembic commands ###
